enableGlobalCache: false

enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: 10

packageExtensions:
  '@commitlint/cli@*':
    peerDependenciesMeta:
      '@types/node':
        optional: true
      typescript:
        optional: true
  '@commitlint/load@*':
    peerDependenciesMeta:
      '@types/node':
        optional: true
      typescript:
        optional: true
  '@rolldown/binding-wasm32-wasi@*':
    dependencies:
      '@emnapi/core': ^1.7.1
      '@emnapi/runtime': ^1.7.1

yarnPath: .yarn/releases/yarn-4.17.0.cjs
